name: Build Docker
on:
  push:
    branches:
      - "main"
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@3c0a6ca5c66e31614579048b57259114fb69ac28 #1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: rust-tcp-proxy
